<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class MetadataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();
        
        // Insert metadata entities for existing modules
        $entities = [
            // IAM Module
            [
                'name' => 'user',
                'label' => 'User',
                'label_plural' => 'Users',
                'table_name' => 'users',
                'icon' => 'user',
                'module' => 'iam',
                'description' => 'System users with authentication and authorization',
                'is_system' => true,
                'is_active' => true,
                'has_workflow' => false,
                'has_audit_trail' => true,
                'is_tenant_scoped' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'role',
                'label' => 'Role',
                'label_plural' => 'Roles',
                'table_name' => 'roles',
                'icon' => 'shield',
                'module' => 'iam',
                'description' => 'User roles for RBAC',
                'is_system' => true,
                'is_active' => true,
                'has_workflow' => false,
                'has_audit_trail' => true,
                'is_tenant_scoped' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'permission',
                'label' => 'Permission',
                'label_plural' => 'Permissions',
                'table_name' => 'permissions',
                'icon' => 'key',
                'module' => 'iam',
                'description' => 'System permissions',
                'is_system' => true,
                'is_active' => true,
                'has_workflow' => false,
                'has_audit_trail' => true,
                'is_tenant_scoped' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // Inventory Module
            [
                'name' => 'product',
                'label' => 'Product',
                'label_plural' => 'Products',
                'table_name' => 'products',
                'icon' => 'package',
                'module' => 'inventory',
                'description' => 'Products and inventory items',
                'is_system' => false,
                'is_active' => true,
                'has_workflow' => true,
                'has_audit_trail' => true,
                'is_tenant_scoped' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'stock_ledger',
                'label' => 'Stock Ledger Entry',
                'label_plural' => 'Stock Ledger',
                'table_name' => 'stock_ledgers',
                'icon' => 'list',
                'module' => 'inventory',
                'description' => 'Append-only stock movement history',
                'is_system' => true,
                'is_active' => true,
                'has_workflow' => false,
                'has_audit_trail' => true,
                'is_tenant_scoped' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // CRM Module
            [
                'name' => 'customer',
                'label' => 'Customer',
                'label_plural' => 'Customers',
                'table_name' => 'customers',
                'icon' => 'users',
                'module' => 'crm',
                'description' => 'Customer accounts and contacts',
                'is_system' => false,
                'is_active' => true,
                'has_workflow' => false,
                'has_audit_trail' => true,
                'is_tenant_scoped' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // Procurement Module
            [
                'name' => 'supplier',
                'label' => 'Supplier',
                'label_plural' => 'Suppliers',
                'table_name' => 'suppliers',
                'icon' => 'truck',
                'module' => 'procurement',
                'description' => 'Supplier management',
                'is_system' => false,
                'is_active' => true,
                'has_workflow' => false,
                'has_audit_trail' => true,
                'is_tenant_scoped' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'purchase_order',
                'label' => 'Purchase Order',
                'label_plural' => 'Purchase Orders',
                'table_name' => 'purchase_orders',
                'icon' => 'shopping-cart',
                'module' => 'procurement',
                'description' => 'Purchase orders to suppliers',
                'is_system' => false,
                'is_active' => true,
                'has_workflow' => true,
                'has_audit_trail' => true,
                'is_tenant_scoped' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // POS Module
            [
                'name' => 'quotation',
                'label' => 'Quotation',
                'label_plural' => 'Quotations',
                'table_name' => 'quotations',
                'icon' => 'file-text',
                'module' => 'pos',
                'description' => 'Sales quotations',
                'is_system' => false,
                'is_active' => true,
                'has_workflow' => true,
                'has_audit_trail' => true,
                'is_tenant_scoped' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'sales_order',
                'label' => 'Sales Order',
                'label_plural' => 'Sales Orders',
                'table_name' => 'sales_orders',
                'icon' => 'shopping-bag',
                'module' => 'pos',
                'description' => 'Customer sales orders',
                'is_system' => false,
                'is_active' => true,
                'has_workflow' => true,
                'has_audit_trail' => true,
                'is_tenant_scoped' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'invoice',
                'label' => 'Invoice',
                'label_plural' => 'Invoices',
                'table_name' => 'invoices',
                'icon' => 'file-invoice',
                'module' => 'pos',
                'description' => 'Sales invoices',
                'is_system' => false,
                'is_active' => true,
                'has_workflow' => true,
                'has_audit_trail' => true,
                'is_tenant_scoped' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'payment',
                'label' => 'Payment',
                'label_plural' => 'Payments',
                'table_name' => 'payments',
                'icon' => 'credit-card',
                'module' => 'pos',
                'description' => 'Payment transactions',
                'is_system' => false,
                'is_active' => true,
                'has_workflow' => false,
                'has_audit_trail' => true,
                'is_tenant_scoped' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // Manufacturing Module
            [
                'name' => 'bom',
                'label' => 'Bill of Materials',
                'label_plural' => 'Bills of Materials',
                'table_name' => 'bills_of_materials',
                'icon' => 'list-alt',
                'module' => 'manufacturing',
                'description' => 'Product BOMs',
                'is_system' => false,
                'is_active' => true,
                'has_workflow' => false,
                'has_audit_trail' => true,
                'is_tenant_scoped' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'production_order',
                'label' => 'Production Order',
                'label_plural' => 'Production Orders',
                'table_name' => 'production_orders',
                'icon' => 'industry',
                'module' => 'manufacturing',
                'description' => 'Manufacturing production orders',
                'is_system' => false,
                'is_active' => true,
                'has_workflow' => true,
                'has_audit_trail' => true,
                'is_tenant_scoped' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'work_order',
                'label' => 'Work Order',
                'label_plural' => 'Work Orders',
                'table_name' => 'work_orders',
                'icon' => 'wrench',
                'module' => 'manufacturing',
                'description' => 'Manufacturing work orders',
                'is_system' => false,
                'is_active' => true,
                'has_workflow' => true,
                'has_audit_trail' => true,
                'is_tenant_scoped' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // Finance Module
            [
                'name' => 'account',
                'label' => 'Account',
                'label_plural' => 'Chart of Accounts',
                'table_name' => 'accounts',
                'icon' => 'book',
                'module' => 'finance',
                'description' => 'Chart of accounts',
                'is_system' => false,
                'is_active' => true,
                'has_workflow' => false,
                'has_audit_trail' => true,
                'is_tenant_scoped' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'journal_entry',
                'label' => 'Journal Entry',
                'label_plural' => 'Journal Entries',
                'table_name' => 'journal_entries',
                'icon' => 'edit',
                'module' => 'finance',
                'description' => 'Accounting journal entries',
                'is_system' => false,
                'is_active' => true,
                'has_workflow' => true,
                'has_audit_trail' => true,
                'is_tenant_scoped' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // Reporting Module
            [
                'name' => 'report',
                'label' => 'Report',
                'label_plural' => 'Reports',
                'table_name' => 'reports',
                'icon' => 'chart-bar',
                'module' => 'reporting',
                'description' => 'Custom reports',
                'is_system' => false,
                'is_active' => true,
                'has_workflow' => false,
                'has_audit_trail' => true,
                'is_tenant_scoped' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'dashboard',
                'label' => 'Dashboard',
                'label_plural' => 'Dashboards',
                'table_name' => 'dashboards',
                'icon' => 'tachometer-alt',
                'module' => 'reporting',
                'description' => 'Analytics dashboards',
                'is_system' => false,
                'is_active' => true,
                'has_workflow' => false,
                'has_audit_trail' => true,
                'is_tenant_scoped' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('metadata_entities')->insert($entities);

        $this->command->info('Metadata entities seeded successfully!');
    }
}
